import { ExerciseTemplate } from '@/store/api/trainingApi';

export const mockExercises: ExerciseTemplate[] = [
  // STRENGTH MODE EXERCISES
  {
    id: 'ex-strength-001',
    name: 'Back Squat',
    category: 'compound_movements',
    description: 'Traditional back squat for maximum strength development',
    instructions: 'Descend to below parallel, drive through heels',
    sets: 4,
    reps: 5,
    duration: 0,
    restPeriod: 180,
    equipment: ['Barbell', 'Squat Rack', 'Weight Plates'],
    muscleGroups: ['Quadriceps', 'Glutes', 'Core'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep chest up', 'Knees track over toes', 'Tight core'],
    tags: ['compound_movements', 'bilateral', 'heavy_resistance'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-strength-002',
    name: 'Deadlift',
    category: 'compound_movements',
    description: 'Hip hinge movement for posterior chain strength',
    instructions: 'Maintain neutral spine, drive hips forward',
    sets: 3,
    reps: 5,
    duration: 0,
    restPeriod: 240,
    equipment: ['Barbell', 'Weight Plates', 'Platform'],
    muscleGroups: ['Hamstrings', 'Glutes', 'Back', 'Core'],
    difficulty: 'advanced',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Straight bar path', 'Engage lats', 'Full hip extension'],
    tags: ['compound_movements', 'multi_joint', 'heavy_resistance'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // POWER MODE EXERCISES
  {
    id: 'ex-power-001',
    name: 'Power Clean',
    category: 'olympic_lifts',
    description: 'Explosive full-body power development',
    instructions: 'Triple extension followed by catch in front rack',
    sets: 5,
    reps: 3,
    duration: 0,
    restPeriod: 300,
    equipment: ['Olympic Barbell', 'Bumper Plates', 'Platform'],
    muscleGroups: ['Full Body', 'Power'],
    difficulty: 'advanced',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Explosive pull', 'High elbows on catch', 'Fast under the bar'],
    tags: ['olympic_lifts', 'explosive_movements', 'power_training'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-power-002',
    name: 'Medicine Ball Slam',
    category: 'medicine_ball',
    description: 'Explosive overhead to ground power exercise',
    instructions: 'Slam ball with maximum force, full body engagement',
    sets: 4,
    reps: 8,
    duration: 0,
    restPeriod: 120,
    equipment: ['Medicine Ball', 'Open Space'],
    muscleGroups: ['Core', 'Shoulders', 'Full Body'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Full overhead reach', 'Engage core', 'Follow through'],
    tags: ['explosive_movements', 'medicine_ball', 'power_training'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-power-003',
    name: 'Kettlebell Swing',
    category: 'kettlebell_swings',
    description: 'Hip hinge power movement with kettlebell',
    instructions: 'Explosive hip drive, bell to eye level',
    sets: 4,
    reps: 15,
    duration: 0,
    restPeriod: 90,
    equipment: ['Kettlebell'],
    muscleGroups: ['Glutes', 'Hamstrings', 'Core'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Hip hinge not squat', 'Tight glutes at top', 'Control the descent'],
    tags: ['kettlebell_swings', 'explosive_movements', 'power_training'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // STABILITY & CORE MODE EXERCISES
  {
    id: 'ex-stability-001',
    name: 'Single Leg Deadlift',
    category: 'unilateral_movements',
    description: 'Unilateral balance and stability exercise',
    instructions: 'Maintain balance on one leg, reach opposite hand to floor',
    sets: 3,
    reps: 12,
    duration: 0,
    restPeriod: 45,
    equipment: ['Dumbbell', 'Balance Pad'],
    muscleGroups: ['Hamstrings', 'Glutes', 'Core', 'Balance'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep hips square', 'Control the movement', 'Engage core'],
    tags: ['unilateral_movements', 'balance_training', 'stabilization'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-stability-002',
    name: 'Plank Variations',
    category: 'core_exercises',
    description: 'Isometric core stability holds',
    instructions: 'Hold plank position with proper alignment',
    sets: 3,
    reps: 0,
    duration: 45,
    restPeriod: 30,
    equipment: ['None', 'Stability Ball'],
    muscleGroups: ['Core', 'Shoulders'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Straight line head to heels', 'Breathe normally', 'Tight glutes'],
    tags: ['core_exercises', 'stabilization', 'anti_extension'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-stability-003',
    name: 'Bird Dog',
    category: 'stabilization',
    description: 'Contralateral stability and core activation',
    instructions: 'Opposite arm and leg extension while maintaining neutral spine',
    sets: 3,
    reps: 10,
    duration: 0,
    restPeriod: 30,
    equipment: ['None'],
    muscleGroups: ['Core', 'Glutes', 'Back'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['No hip rotation', 'Reach long', 'Keep hips level'],
    tags: ['stabilization', 'core_exercises', 'balance_training'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // PLYOMETRICS MODE EXERCISES
  {
    id: 'ex-plyo-001',
    name: 'Box Jump',
    category: 'jump_training',
    description: 'Vertical power development with landing mechanics',
    instructions: 'Jump onto box, step down, focus on soft landing',
    sets: 4,
    reps: 6,
    duration: 0,
    restPeriod: 120,
    equipment: ['Plyo Box', 'Open Space'],
    muscleGroups: ['Legs', 'Power', 'Landing'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Soft landing', 'Full hip extension', 'Arms drive up'],
    tags: ['jump_training', 'reactive_training', 'landing_mechanics'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-plyo-002',
    name: 'Depth Jump',
    category: 'reactive_training',
    description: 'Reactive strength index development',
    instructions: 'Step off box, land and immediately jump for maximum height',
    sets: 3,
    reps: 5,
    duration: 0,
    restPeriod: 180,
    equipment: ['Plyo Box', 'Force Plate'],
    muscleGroups: ['Legs', 'Reactive', 'Power'],
    difficulty: 'advanced',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Minimal ground contact', 'Maximum height', 'Pre-tension muscles'],
    tags: ['reactive_training', 'depth_jumps', 'landing_mechanics'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-plyo-003',
    name: 'Lateral Bounds',
    category: 'bounding',
    description: 'Lateral power and stability development',
    instructions: 'Bound side to side, stick each landing for 2 seconds',
    sets: 3,
    reps: 8,
    duration: 0,
    restPeriod: 90,
    equipment: ['Cones', 'Open Space'],
    muscleGroups: ['Legs', 'Hip Stability', 'Lateral Power'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Stick the landing', 'Drive off outside leg', 'Control deceleration'],
    tags: ['bounding', 'lateral_movement', 'landing_mechanics'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // ORIGINAL EXERCISES CONTINUE...
  // Warm-up Exercises
  {
    id: 'ex-001',
    name: 'Dynamic Stretching Circuit',
    category: 'warmup',
    description: 'Full body dynamic warm-up routine',
    instructions: 'Perform each movement for 30 seconds with smooth, controlled motions',
    sets: 1,
    reps: 10,
    duration: 300,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Full Body'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep movements controlled', 'Focus on range of motion', 'Breathe steadily'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-002',
    name: 'Foam Rolling',
    category: 'warmup',
    description: 'Self-myofascial release for major muscle groups',
    instructions: 'Roll each muscle group for 60-90 seconds',
    sets: 1,
    reps: 0,
    duration: 600,
    restPeriod: 0,
    equipment: ['Foam Roller'],
    muscleGroups: ['Full Body'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Apply moderate pressure', 'Roll slowly', 'Pause on tight spots'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-003',
    name: 'Leg Swings',
    category: 'warmup',
    description: 'Dynamic hip mobility exercise',
    instructions: 'Perform 15 swings forward/back and side to side each leg',
    sets: 2,
    reps: 15,
    duration: 0,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Hips', 'Legs'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Hold wall for balance', 'Control the swing', 'Keep core engaged'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-004',
    name: 'Arm Circles',
    category: 'warmup',
    description: 'Shoulder mobility warm-up',
    instructions: 'Perform small to large circles, forward and backward',
    sets: 2,
    reps: 20,
    duration: 0,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Shoulders'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Start small, increase size', 'Keep arms straight', 'Control the movement'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Main Strength Exercises
  {
    id: 'ex-005',
    name: 'Barbell Back Squat',
    category: 'main',
    description: 'Fundamental lower body strength exercise',
    instructions: 'Squat down to parallel or below while maintaining proper form',
    sets: 4,
    reps: 8,
    duration: 0,
    restPeriod: 120,
    equipment: ['Barbell', 'Squat Rack', 'Weight Plates'],
    muscleGroups: ['Quadriceps', 'Glutes', 'Hamstrings'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep chest up', 'Drive through heels', 'Maintain neutral spine', 'Control descent'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-006',
    name: 'Bench Press',
    category: 'main',
    description: 'Primary upper body pushing exercise',
    instructions: 'Lower bar to chest with control, press back to start position',
    sets: 4,
    reps: 8,
    duration: 0,
    restPeriod: 90,
    equipment: ['Barbell', 'Bench', 'Weight Plates'],
    muscleGroups: ['Chest', 'Shoulders', 'Triceps'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Retract shoulder blades', 'Maintain arch', 'Control bar path', 'Full range of motion'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-007',
    name: 'Deadlift',
    category: 'main',
    description: 'Full body power and strength exercise',
    instructions: 'Lift barbell from floor to hip level with proper form',
    sets: 3,
    reps: 5,
    duration: 0,
    restPeriod: 180,
    equipment: ['Barbell', 'Weight Plates'],
    muscleGroups: ['Back', 'Glutes', 'Hamstrings', 'Core'],
    difficulty: 'advanced',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Neutral spine', 'Engage lats', 'Drive hips forward', 'Lock out at top'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-008',
    name: 'Pull-ups',
    category: 'main',
    description: 'Upper body pulling exercise',
    instructions: 'Pull body up until chin clears the bar',
    sets: 4,
    reps: 8,
    duration: 0,
    restPeriod: 90,
    equipment: ['Pull-up Bar'],
    muscleGroups: ['Back', 'Biceps', 'Core'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Full hang at bottom', 'Pull elbows down', 'Control descent', 'Engage core'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-009',
    name: 'Box Jumps',
    category: 'main',
    description: 'Explosive power development exercise',
    instructions: 'Jump onto box, step down, repeat',
    sets: 4,
    reps: 6,
    duration: 0,
    restPeriod: 60,
    equipment: ['Plyo Box'],
    muscleGroups: ['Legs', 'Glutes'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Land softly', 'Full hip extension', 'Step down safely', 'Reset between reps'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Accessory Exercises
  {
    id: 'ex-010',
    name: 'Dumbbell Lunges',
    category: 'accessory',
    description: 'Unilateral leg strength exercise',
    instructions: 'Step forward into lunge position, return to start',
    sets: 3,
    reps: 12,
    duration: 0,
    restPeriod: 60,
    equipment: ['Dumbbells'],
    muscleGroups: ['Quadriceps', 'Glutes', 'Hamstrings'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Knee over ankle', 'Back knee down', 'Maintain balance', 'Push through front heel'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-011',
    name: 'Face Pulls',
    category: 'accessory',
    description: 'Rear deltoid and upper back exercise',
    instructions: 'Pull rope to face level, squeeze shoulder blades',
    sets: 3,
    reps: 15,
    duration: 0,
    restPeriod: 45,
    equipment: ['Cable Machine', 'Rope Attachment'],
    muscleGroups: ['Shoulders', 'Upper Back'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Pull to eye level', 'Elbows high', 'Squeeze at end', 'Control return'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-012',
    name: 'Bicep Curls',
    category: 'accessory',
    description: 'Isolated bicep exercise',
    instructions: 'Curl dumbbells from hip to shoulder',
    sets: 3,
    reps: 12,
    duration: 0,
    restPeriod: 45,
    equipment: ['Dumbbells'],
    muscleGroups: ['Biceps'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep elbows stable', 'Full range of motion', 'Control tempo', 'No swinging'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-013',
    name: 'Calf Raises',
    category: 'accessory',
    description: 'Lower leg strength exercise',
    instructions: 'Rise up on toes, lower with control',
    sets: 3,
    reps: 20,
    duration: 0,
    restPeriod: 45,
    equipment: ['Dumbbells'],
    muscleGroups: ['Calves'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Full range of motion', 'Pause at top', 'Control descent', 'Keep balance'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Core Exercises
  {
    id: 'ex-014',
    name: 'Plank',
    category: 'core',
    description: 'Isometric core stability exercise',
    instructions: 'Hold plank position for prescribed time',
    sets: 3,
    reps: 0,
    duration: 60,
    restPeriod: 30,
    equipment: ['None'],
    muscleGroups: ['Core', 'Shoulders'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Neutral spine', 'Engage core', 'Breathe normally', 'Keep hips level'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-015',
    name: 'Russian Twists',
    category: 'core',
    description: 'Rotational core exercise',
    instructions: 'Rotate torso side to side while holding weight',
    sets: 3,
    reps: 20,
    duration: 0,
    restPeriod: 45,
    equipment: ['Medicine Ball'],
    muscleGroups: ['Core', 'Obliques'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep chest up', 'Control rotation', 'Engage core', 'Breathe steadily'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-016',
    name: 'Dead Bug',
    category: 'core',
    description: 'Core stability and coordination exercise',
    instructions: 'Extend opposite arm and leg while maintaining neutral spine',
    sets: 3,
    reps: 10,
    duration: 0,
    restPeriod: 30,
    equipment: ['None'],
    muscleGroups: ['Core'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Press lower back down', 'Move slowly', 'Breathe out on extension', 'Return to start'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-017',
    name: 'Pallof Press',
    category: 'core',
    description: 'Anti-rotation core exercise',
    instructions: 'Press cable straight out, resist rotation',
    sets: 3,
    reps: 12,
    duration: 0,
    restPeriod: 45,
    equipment: ['Cable Machine'],
    muscleGroups: ['Core', 'Obliques'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Resist rotation', 'Keep arms straight', 'Engage core', 'Control movement'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Cool-down Exercises
  {
    id: 'ex-018',
    name: 'Static Hamstring Stretch',
    category: 'cooldown',
    description: 'Static stretch for hamstring flexibility',
    instructions: 'Hold stretch for 30-60 seconds each leg',
    sets: 2,
    reps: 0,
    duration: 60,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Hamstrings'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Gentle stretch', 'No bouncing', 'Breathe deeply', 'Relax into stretch'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-019',
    name: 'Quad Stretch',
    category: 'cooldown',
    description: 'Static quadriceps stretch',
    instructions: 'Pull heel to glute, hold for 30-60 seconds',
    sets: 2,
    reps: 0,
    duration: 60,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Quadriceps'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep knees together', 'Stand tall', 'Use wall for balance', 'Feel stretch in front of thigh'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-020',
    name: 'Child\'s Pose',
    category: 'cooldown',
    description: 'Relaxation and back stretch',
    instructions: 'Hold position for 1-2 minutes',
    sets: 1,
    reps: 0,
    duration: 120,
    restPeriod: 0,
    equipment: ['Yoga Mat'],
    muscleGroups: ['Back', 'Shoulders'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Breathe deeply', 'Relax shoulders', 'Sink into stretch', 'Clear your mind'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-021',
    name: 'Walking Recovery',
    category: 'cooldown',
    description: 'Light walking to reduce heart rate',
    instructions: 'Walk at easy pace for 5 minutes',
    sets: 1,
    reps: 0,
    duration: 300,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Full Body'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Easy pace', 'Focus on breathing', 'Relax shoulders', 'Gradually slow down'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Hockey-Specific Exercises
  {
    id: 'ex-022',
    name: 'Single Leg Bounds',
    category: 'main',
    description: 'Hockey-specific power exercise mimicking skating stride',
    instructions: 'Bound laterally from one leg to the other',
    sets: 4,
    reps: 10,
    duration: 0,
    restPeriod: 60,
    equipment: ['None'],
    muscleGroups: ['Legs', 'Glutes', 'Core'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Land softly', 'Push off explosively', 'Maintain balance', 'Mimic skating motion'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-023',
    name: 'Medicine Ball Rotational Throws',
    category: 'main',
    description: 'Develop rotational power for shooting',
    instructions: 'Rotate and throw medicine ball against wall',
    sets: 3,
    reps: 10,
    duration: 0,
    restPeriod: 60,
    equipment: ['Medicine Ball', 'Wall'],
    muscleGroups: ['Core', 'Obliques', 'Shoulders'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Generate power from hips', 'Follow through', 'Catch and reset', 'Explosive rotation'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-024',
    name: 'Lateral Lunges',
    category: 'accessory',
    description: 'Strengthen muscles used in skating',
    instructions: 'Step laterally into lunge position, push back to start',
    sets: 3,
    reps: 12,
    duration: 0,
    restPeriod: 45,
    equipment: ['Dumbbells'],
    muscleGroups: ['Adductors', 'Glutes', 'Quadriceps'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep chest up', 'Push hips back', 'Drive off outside leg', 'Control movement'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-025',
    name: 'Cable Woodchops',
    category: 'accessory',
    description: 'Rotational strength for shooting power',
    instructions: 'Pull cable diagonally across body',
    sets: 3,
    reps: 12,
    duration: 0,
    restPeriod: 45,
    equipment: ['Cable Machine'],
    muscleGroups: ['Core', 'Obliques', 'Shoulders'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Rotate from core', 'Keep arms straight', 'Control return', 'Full range of motion'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  
  // Plyometric Exercises
  {
    id: 'ex-026',
    name: 'Depth Jumps',
    category: 'main',
    description: 'Advanced plyometric exercise for explosive power',
    instructions: 'Step off box, land and immediately jump as high as possible',
    sets: 4,
    reps: 5,
    duration: 0,
    restPeriod: 120,
    equipment: ['Plyo Box'],
    muscleGroups: ['Legs', 'Glutes'],
    difficulty: 'advanced',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Step off, don\'t jump', 'Minimal ground contact', 'Maximum vertical jump', 'Full recovery between reps'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-027',
    name: 'Broad Jumps',
    category: 'main',
    description: 'Horizontal plyometric power exercise',
    instructions: 'Jump forward as far as possible, stick the landing',
    sets: 4,
    reps: 5,
    duration: 0,
    restPeriod: 90,
    equipment: ['None'],
    muscleGroups: ['Legs', 'Glutes', 'Core'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Use arms for momentum', 'Drive hips forward', 'Stick landing', 'Reset between jumps'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-028',
    name: 'Split Squat Jumps',
    category: 'main',
    description: 'Plyometric lunge variation for single leg power',
    instructions: 'Jump and switch legs in air, land in lunge position',
    sets: 3,
    reps: 12,
    duration: 0,
    restPeriod: 60,
    equipment: ['None'],
    muscleGroups: ['Legs', 'Glutes'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Land softly', 'Keep chest up', 'Drive through legs', 'Control landing'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-029',
    name: 'Lateral Box Jumps',
    category: 'main',
    description: 'Side-to-side plyometric exercise',
    instructions: 'Jump laterally onto box, step down, repeat',
    sets: 3,
    reps: 8,
    duration: 0,
    restPeriod: 60,
    equipment: ['Plyo Box'],
    muscleGroups: ['Legs', 'Glutes', 'Abductors'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Land balanced', 'Full hip extension', 'Control lateral movement', 'Step down safely'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-030',
    name: 'Medicine Ball Slams',
    category: 'main',
    description: 'Full body explosive power exercise',
    instructions: 'Raise ball overhead and slam down with maximum force',
    sets: 4,
    reps: 10,
    duration: 0,
    restPeriod: 60,
    equipment: ['Medicine Ball'],
    muscleGroups: ['Core', 'Shoulders', 'Full Body'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Full extension at top', 'Slam with force', 'Engage core', 'Follow through'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Running Drills
  {
    id: 'ex-031',
    name: 'High Knees',
    category: 'warmup',
    description: 'Dynamic running drill for hip flexor activation',
    instructions: 'Run in place bringing knees to hip level',
    sets: 3,
    reps: 0,
    duration: 30,
    restPeriod: 30,
    equipment: ['None'],
    muscleGroups: ['Hip Flexors', 'Calves', 'Core'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Drive knees up', 'Land on balls of feet', 'Pump arms', 'Quick ground contact'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-032',
    name: 'Butt Kicks',
    category: 'warmup',
    description: 'Dynamic hamstring activation drill',
    instructions: 'Run in place kicking heels to glutes',
    sets: 3,
    reps: 0,
    duration: 30,
    restPeriod: 30,
    equipment: ['None'],
    muscleGroups: ['Hamstrings', 'Calves'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Heels to glutes', 'Stay on toes', 'Quick tempo', 'Minimal forward movement'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-033',
    name: 'A-Skips',
    category: 'warmup',
    description: 'Technical running drill for form improvement',
    instructions: 'Skip with high knee drive and proper arm action',
    sets: 3,
    reps: 0,
    duration: 0,
    distance: 20,
    restPeriod: 45,
    equipment: ['None'],
    muscleGroups: ['Hip Flexors', 'Calves', 'Core'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Drive knee up', 'Opposite arm action', 'Land on forefoot', 'Maintain rhythm'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-034',
    name: 'B-Skips',
    category: 'warmup',
    description: 'Advanced running drill with leg extension',
    instructions: 'A-skip with leg extension before ground contact',
    sets: 3,
    reps: 0,
    duration: 0,
    distance: 20,
    restPeriod: 45,
    equipment: ['None'],
    muscleGroups: ['Hip Flexors', 'Hamstrings', 'Calves'],
    difficulty: 'advanced',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Knee up then extend', 'Pawing motion', 'Quick ground contact', 'Coordinate arms'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-035',
    name: 'Carioca',
    category: 'warmup',
    description: 'Lateral movement drill for coordination',
    instructions: 'Cross step laterally alternating front and back',
    sets: 2,
    reps: 0,
    duration: 0,
    distance: 20,
    restPeriod: 30,
    equipment: ['None'],
    muscleGroups: ['Hips', 'Core', 'Legs'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Stay low', 'Quick feet', 'Rotate hips', 'Keep shoulders square'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Dynamic Movement Exercises
  {
    id: 'ex-036',
    name: 'Walking Lunges',
    category: 'warmup',
    description: 'Dynamic lower body warm-up exercise',
    instructions: 'Step forward into lunge, continue walking',
    sets: 2,
    reps: 10,
    duration: 0,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Quadriceps', 'Glutes', 'Hip Flexors'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Long steps', 'Knee over ankle', 'Push through heel', 'Keep torso upright'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-037',
    name: 'Inchworms',
    category: 'warmup',
    description: 'Full body dynamic warm-up exercise',
    instructions: 'Walk hands out to plank, walk feet to hands',
    sets: 2,
    reps: 8,
    duration: 0,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Core', 'Shoulders', 'Hamstrings'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep legs straight', 'Walk hands out', 'Hold plank briefly', 'Walk feet forward'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-038',
    name: 'Lateral Lunges',
    category: 'warmup',
    description: 'Dynamic groin and hip mobility exercise',
    instructions: 'Step laterally into wide lunge, push back to start',
    sets: 2,
    reps: 10,
    duration: 0,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Adductors', 'Glutes', 'Quadriceps'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Wide step', 'Push hips back', 'Keep chest up', 'Drive off outside leg'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-039',
    name: 'Hip Circles',
    category: 'warmup',
    description: 'Hip mobility and activation exercise',
    instructions: 'Large circles with hips, both directions',
    sets: 2,
    reps: 10,
    duration: 0,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Hips', 'Core'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Large circles', 'Control movement', 'Both directions', 'Keep upper body stable'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-040',
    name: 'Scorpion Stretch',
    category: 'warmup',
    description: 'Dynamic spine and hip mobility exercise',
    instructions: 'Lying face down, rotate leg across body',
    sets: 2,
    reps: 8,
    duration: 0,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Spine', 'Hips', 'Core'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Control rotation', 'Keep shoulders down', 'Feel stretch through spine', 'Alternate sides'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Cooldown and Recovery Exercises
  {
    id: 'ex-041',
    name: 'Seated Forward Fold',
    category: 'cooldown',
    description: 'Static hamstring and back stretch',
    instructions: 'Sit with legs extended, fold forward reaching for toes',
    sets: 2,
    reps: 0,
    duration: 60,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Hamstrings', 'Lower Back'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Breathe deeply', 'Relax into stretch', 'Don\'t force it', 'Keep spine long'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-042',
    name: 'Pigeon Pose',
    category: 'cooldown',
    description: 'Deep hip flexor and glute stretch',
    instructions: 'One leg forward bent, other extended back',
    sets: 2,
    reps: 0,
    duration: 90,
    restPeriod: 0,
    equipment: ['Yoga Mat'],
    muscleGroups: ['Hip Flexors', 'Glutes'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Square hips', 'Sink into stretch', 'Breathe deeply', 'Support with hands'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-043',
    name: 'Calf Stretch',
    category: 'cooldown',
    description: 'Static calf muscle stretch',
    instructions: 'Press heel down in lunge position',
    sets: 2,
    reps: 0,
    duration: 45,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Calves'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep heel down', 'Lean forward', 'Feel stretch in calf', 'Hold steady'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-044',
    name: 'Shoulder Cross-Body Stretch',
    category: 'cooldown',
    description: 'Shoulder and upper back stretch',
    instructions: 'Pull arm across body with opposite hand',
    sets: 2,
    reps: 0,
    duration: 45,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Shoulders', 'Upper Back'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep shoulder down', 'Pull gently', 'Feel stretch in shoulder', 'Switch sides'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-045',
    name: 'Foam Roll IT Band',
    category: 'cooldown',
    description: 'Self-myofascial release for IT band',
    instructions: 'Roll outer thigh from hip to knee',
    sets: 2,
    reps: 0,
    duration: 90,
    restPeriod: 0,
    equipment: ['Foam Roller'],
    muscleGroups: ['IT Band', 'Outer Thigh'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Support with arms', 'Roll slowly', 'Pause on tender spots', 'Control pressure'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Hockey-Specific Conditioning
  {
    id: 'ex-046',
    name: 'Skating Stride Simulation',
    category: 'main',
    description: 'Off-ice skating movement pattern',
    instructions: 'Lateral push-offs mimicking skating stride',
    sets: 4,
    reps: 20,
    duration: 0,
    restPeriod: 60,
    equipment: ['None'],
    muscleGroups: ['Legs', 'Glutes', 'Core'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Low position', 'Full extension', 'Drive laterally', 'Mimic skating rhythm'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-047',
    name: 'Quick Feet Ladder',
    category: 'main',
    description: 'Foot speed development for hockey',
    instructions: 'Various ladder patterns at maximum speed',
    sets: 5,
    reps: 1,
    duration: 0,
    restPeriod: 45,
    equipment: ['Agility Ladder'],
    muscleGroups: ['Feet', 'Calves', 'Hip Flexors'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Light on feet', 'Quick ground contact', 'Stay low', 'Maintain rhythm'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-048',
    name: 'Battle Ropes Waves',
    category: 'main',
    description: 'Upper body power endurance for hockey',
    instructions: 'Alternating arm waves with battle ropes',
    sets: 4,
    reps: 0,
    duration: 30,
    restPeriod: 45,
    equipment: ['Battle Ropes'],
    muscleGroups: ['Shoulders', 'Arms', 'Core'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Athletic stance', 'Generate from core', 'Consistent waves', 'Breathe steadily'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-049',
    name: 'Slide Board Lateral Movement',
    category: 'main',
    description: 'Hockey-specific lateral conditioning',
    instructions: 'Slide side to side on slide board',
    sets: 3,
    reps: 0,
    duration: 60,
    restPeriod: 90,
    equipment: ['Slide Board'],
    muscleGroups: ['Legs', 'Glutes', 'Abductors'],
    difficulty: 'advanced',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Stay low', 'Full push-off', 'Control landing', 'Mimic skating position'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-050',
    name: 'Sprint Starts',
    category: 'main',
    description: 'Explosive acceleration training',
    instructions: '10-yard sprints from various starting positions',
    sets: 6,
    reps: 1,
    duration: 0,
    distance: 10,
    restPeriod: 90,
    equipment: ['None'],
    muscleGroups: ['Legs', 'Glutes', 'Core'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Explosive start', 'Drive arms', 'Forward lean', 'Maximum effort'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  }
];