import { ExerciseTemplate } from '@/store/api/trainingApi';

export const mockExercises: ExerciseTemplate[] = [
  // Warm-up Exercises
  {
    id: 'ex-001',
    name: 'Dynamic Stretching Circuit',
    category: 'warmup',
    description: 'Full body dynamic warm-up routine',
    instructions: 'Perform each movement for 30 seconds with smooth, controlled motions',
    sets: 1,
    reps: 10,
    duration: 300,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Full Body'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep movements controlled', 'Focus on range of motion', 'Breathe steadily'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-002',
    name: 'Foam Rolling',
    category: 'warmup',
    description: 'Self-myofascial release for major muscle groups',
    instructions: 'Roll each muscle group for 60-90 seconds',
    sets: 1,
    reps: 0,
    duration: 600,
    restPeriod: 0,
    equipment: ['Foam Roller'],
    muscleGroups: ['Full Body'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Apply moderate pressure', 'Roll slowly', 'Pause on tight spots'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-003',
    name: 'Leg Swings',
    category: 'warmup',
    description: 'Dynamic hip mobility exercise',
    instructions: 'Perform 15 swings forward/back and side to side each leg',
    sets: 2,
    reps: 15,
    duration: 0,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Hips', 'Legs'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Hold wall for balance', 'Control the swing', 'Keep core engaged'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-004',
    name: 'Arm Circles',
    category: 'warmup',
    description: 'Shoulder mobility warm-up',
    instructions: 'Perform small to large circles, forward and backward',
    sets: 2,
    reps: 20,
    duration: 0,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Shoulders'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Start small, increase size', 'Keep arms straight', 'Control the movement'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Main Strength Exercises
  {
    id: 'ex-005',
    name: 'Barbell Back Squat',
    category: 'main',
    description: 'Fundamental lower body strength exercise',
    instructions: 'Squat down to parallel or below while maintaining proper form',
    sets: 4,
    reps: 8,
    duration: 0,
    restPeriod: 120,
    equipment: ['Barbell', 'Squat Rack', 'Weight Plates'],
    muscleGroups: ['Quadriceps', 'Glutes', 'Hamstrings'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep chest up', 'Drive through heels', 'Maintain neutral spine', 'Control descent'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-006',
    name: 'Bench Press',
    category: 'main',
    description: 'Primary upper body pushing exercise',
    instructions: 'Lower bar to chest with control, press back to start position',
    sets: 4,
    reps: 8,
    duration: 0,
    restPeriod: 90,
    equipment: ['Barbell', 'Bench', 'Weight Plates'],
    muscleGroups: ['Chest', 'Shoulders', 'Triceps'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Retract shoulder blades', 'Maintain arch', 'Control bar path', 'Full range of motion'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-007',
    name: 'Deadlift',
    category: 'main',
    description: 'Full body power and strength exercise',
    instructions: 'Lift barbell from floor to hip level with proper form',
    sets: 3,
    reps: 5,
    duration: 0,
    restPeriod: 180,
    equipment: ['Barbell', 'Weight Plates'],
    muscleGroups: ['Back', 'Glutes', 'Hamstrings', 'Core'],
    difficulty: 'advanced',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Neutral spine', 'Engage lats', 'Drive hips forward', 'Lock out at top'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-008',
    name: 'Pull-ups',
    category: 'main',
    description: 'Upper body pulling exercise',
    instructions: 'Pull body up until chin clears the bar',
    sets: 4,
    reps: 8,
    duration: 0,
    restPeriod: 90,
    equipment: ['Pull-up Bar'],
    muscleGroups: ['Back', 'Biceps', 'Core'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Full hang at bottom', 'Pull elbows down', 'Control descent', 'Engage core'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-009',
    name: 'Box Jumps',
    category: 'main',
    description: 'Explosive power development exercise',
    instructions: 'Jump onto box, step down, repeat',
    sets: 4,
    reps: 6,
    duration: 0,
    restPeriod: 60,
    equipment: ['Plyo Box'],
    muscleGroups: ['Legs', 'Glutes'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Land softly', 'Full hip extension', 'Step down safely', 'Reset between reps'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Accessory Exercises
  {
    id: 'ex-010',
    name: 'Dumbbell Lunges',
    category: 'accessory',
    description: 'Unilateral leg strength exercise',
    instructions: 'Step forward into lunge position, return to start',
    sets: 3,
    reps: 12,
    duration: 0,
    restPeriod: 60,
    equipment: ['Dumbbells'],
    muscleGroups: ['Quadriceps', 'Glutes', 'Hamstrings'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Knee over ankle', 'Back knee down', 'Maintain balance', 'Push through front heel'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-011',
    name: 'Face Pulls',
    category: 'accessory',
    description: 'Rear deltoid and upper back exercise',
    instructions: 'Pull rope to face level, squeeze shoulder blades',
    sets: 3,
    reps: 15,
    duration: 0,
    restPeriod: 45,
    equipment: ['Cable Machine', 'Rope Attachment'],
    muscleGroups: ['Shoulders', 'Upper Back'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Pull to eye level', 'Elbows high', 'Squeeze at end', 'Control return'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-012',
    name: 'Bicep Curls',
    category: 'accessory',
    description: 'Isolated bicep exercise',
    instructions: 'Curl dumbbells from hip to shoulder',
    sets: 3,
    reps: 12,
    duration: 0,
    restPeriod: 45,
    equipment: ['Dumbbells'],
    muscleGroups: ['Biceps'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep elbows stable', 'Full range of motion', 'Control tempo', 'No swinging'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-013',
    name: 'Calf Raises',
    category: 'accessory',
    description: 'Lower leg strength exercise',
    instructions: 'Rise up on toes, lower with control',
    sets: 3,
    reps: 20,
    duration: 0,
    restPeriod: 45,
    equipment: ['Dumbbells'],
    muscleGroups: ['Calves'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Full range of motion', 'Pause at top', 'Control descent', 'Keep balance'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Core Exercises
  {
    id: 'ex-014',
    name: 'Plank',
    category: 'core',
    description: 'Isometric core stability exercise',
    instructions: 'Hold plank position for prescribed time',
    sets: 3,
    reps: 0,
    duration: 60,
    restPeriod: 30,
    equipment: ['None'],
    muscleGroups: ['Core', 'Shoulders'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Neutral spine', 'Engage core', 'Breathe normally', 'Keep hips level'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-015',
    name: 'Russian Twists',
    category: 'core',
    description: 'Rotational core exercise',
    instructions: 'Rotate torso side to side while holding weight',
    sets: 3,
    reps: 20,
    duration: 0,
    restPeriod: 45,
    equipment: ['Medicine Ball'],
    muscleGroups: ['Core', 'Obliques'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep chest up', 'Control rotation', 'Engage core', 'Breathe steadily'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-016',
    name: 'Dead Bug',
    category: 'core',
    description: 'Core stability and coordination exercise',
    instructions: 'Extend opposite arm and leg while maintaining neutral spine',
    sets: 3,
    reps: 10,
    duration: 0,
    restPeriod: 30,
    equipment: ['None'],
    muscleGroups: ['Core'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Press lower back down', 'Move slowly', 'Breathe out on extension', 'Return to start'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-017',
    name: 'Pallof Press',
    category: 'core',
    description: 'Anti-rotation core exercise',
    instructions: 'Press cable straight out, resist rotation',
    sets: 3,
    reps: 12,
    duration: 0,
    restPeriod: 45,
    equipment: ['Cable Machine'],
    muscleGroups: ['Core', 'Obliques'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Resist rotation', 'Keep arms straight', 'Engage core', 'Control movement'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Cool-down Exercises
  {
    id: 'ex-018',
    name: 'Static Hamstring Stretch',
    category: 'cooldown',
    description: 'Static stretch for hamstring flexibility',
    instructions: 'Hold stretch for 30-60 seconds each leg',
    sets: 2,
    reps: 0,
    duration: 60,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Hamstrings'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Gentle stretch', 'No bouncing', 'Breathe deeply', 'Relax into stretch'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-019',
    name: 'Quad Stretch',
    category: 'cooldown',
    description: 'Static quadriceps stretch',
    instructions: 'Pull heel to glute, hold for 30-60 seconds',
    sets: 2,
    reps: 0,
    duration: 60,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Quadriceps'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep knees together', 'Stand tall', 'Use wall for balance', 'Feel stretch in front of thigh'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-020',
    name: 'Child\'s Pose',
    category: 'cooldown',
    description: 'Relaxation and back stretch',
    instructions: 'Hold position for 1-2 minutes',
    sets: 1,
    reps: 0,
    duration: 120,
    restPeriod: 0,
    equipment: ['Yoga Mat'],
    muscleGroups: ['Back', 'Shoulders'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Breathe deeply', 'Relax shoulders', 'Sink into stretch', 'Clear your mind'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-021',
    name: 'Walking Recovery',
    category: 'cooldown',
    description: 'Light walking to reduce heart rate',
    instructions: 'Walk at easy pace for 5 minutes',
    sets: 1,
    reps: 0,
    duration: 300,
    restPeriod: 0,
    equipment: ['None'],
    muscleGroups: ['Full Body'],
    difficulty: 'beginner',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Easy pace', 'Focus on breathing', 'Relax shoulders', 'Gradually slow down'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },

  // Hockey-Specific Exercises
  {
    id: 'ex-022',
    name: 'Single Leg Bounds',
    category: 'main',
    description: 'Hockey-specific power exercise mimicking skating stride',
    instructions: 'Bound laterally from one leg to the other',
    sets: 4,
    reps: 10,
    duration: 0,
    restPeriod: 60,
    equipment: ['None'],
    muscleGroups: ['Legs', 'Glutes', 'Core'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Land softly', 'Push off explosively', 'Maintain balance', 'Mimic skating motion'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-023',
    name: 'Medicine Ball Rotational Throws',
    category: 'main',
    description: 'Develop rotational power for shooting',
    instructions: 'Rotate and throw medicine ball against wall',
    sets: 3,
    reps: 10,
    duration: 0,
    restPeriod: 60,
    equipment: ['Medicine Ball', 'Wall'],
    muscleGroups: ['Core', 'Obliques', 'Shoulders'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Generate power from hips', 'Follow through', 'Catch and reset', 'Explosive rotation'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-024',
    name: 'Lateral Lunges',
    category: 'accessory',
    description: 'Strengthen muscles used in skating',
    instructions: 'Step laterally into lunge position, push back to start',
    sets: 3,
    reps: 12,
    duration: 0,
    restPeriod: 45,
    equipment: ['Dumbbells'],
    muscleGroups: ['Adductors', 'Glutes', 'Quadriceps'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Keep chest up', 'Push hips back', 'Drive off outside leg', 'Control movement'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ex-025',
    name: 'Cable Woodchops',
    category: 'accessory',
    description: 'Rotational strength for shooting power',
    instructions: 'Pull cable diagonally across body',
    sets: 3,
    reps: 12,
    duration: 0,
    restPeriod: 45,
    equipment: ['Cable Machine'],
    muscleGroups: ['Core', 'Obliques', 'Shoulders'],
    difficulty: 'intermediate',
    videoUrl: '',
    thumbnailUrl: '',
    coachingCues: ['Rotate from core', 'Keep arms straight', 'Control return', 'Full range of motion'],
    createdBy: 'system',
    createdAt: new Date().toISOString()
  }
];