global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts.yml"

scrape_configs:
  # Frontend metrics
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3002']
    metrics_path: '/api/metrics'

  # API Gateway metrics
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'

  # User Service metrics
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']
    metrics_path: '/metrics'

  # Communication Service metrics
  - job_name: 'communication-service'
    static_configs:
      - targets: ['communication-service:3002']
    metrics_path: '/metrics'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Node.js application metrics
  - job_name: 'nodejs'
    static_configs:
      - targets: ['frontend:3002', 'api-gateway:3000', 'user-service:3001', 'communication-service:3002']
    metrics_path: '/metrics'
    params:
      format: ['prometheus']