/**
 * Migration utilities for transitioning to standardized API patterns
 * Provides backward compatibility and transformation utilities
 */

import {
  UnifiedWorkout,
  WorkoutType,
  CreateWorkoutRequest as NewCreateWorkoutRequest,
  UpdateWorkoutRequest as NewUpdateWorkoutRequest,
  ListWorkoutsRequest,
  GetWorkoutRequest,
  isApiError,
  fromApiWorkout,
  toApiWorkout,
} from '../../features/physical-trainer/types/api.types';
import {
  CreateWorkoutRequest as LegacyCreateWorkoutRequest,
  UpdateWorkoutRequest as LegacyUpdateWorkoutRequest,
  TrainingSession,
  WorkoutSession,
} from './trainingApi';

// ============================================
// Type Mapping
// ============================================

/**
 * Legacy to new workout type mapping
 */
const WORKOUT_TYPE_MAP: Record<string, WorkoutType> = {
  'strength': 'STRENGTH',
  'cardio': 'CONDITIONING',
  'conditioning': 'CONDITIONING',
  'mixed': 'HYBRID',
  'hybrid': 'HYBRID',
  'skill': 'AGILITY',
  'agility': 'AGILITY',
  'recovery': 'STRENGTH', // Map recovery to strength for now
};

/**
 * New to legacy workout type mapping
 */
const LEGACY_TYPE_MAP: Record<WorkoutType, string> = {
  'STRENGTH': 'strength',
  'CONDITIONING': 'conditioning',
  'HYBRID': 'hybrid',
  'AGILITY': 'agility',
};

// ============================================
// Request Transformations
// ============================================

/**
 * Transform legacy create request to new format
 */
export function transformLegacyCreateRequest(
  legacy: LegacyCreateWorkoutRequest
): NewCreateWorkoutRequest {
  const workoutType = WORKOUT_TYPE_MAP[legacy.type] || 'STRENGTH';
  
  const baseWorkout = {
    id: '', // Will be generated by API
    type: workoutType,
    name: legacy.title,
    description: legacy.description,
    scheduledDate: new Date(legacy.scheduledDate),
    location: legacy.location,
    estimatedDuration: legacy.estimatedDuration,
    assignedPlayerIds: legacy.playerIds,
    assignedTeamIds: legacy.teamId ? [legacy.teamId] : [],
    exercises: legacy.exercises || [],
    settings: legacy.settings,
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  return {
    type: workoutType,
    workout: baseWorkout as any, // Type assertion for workout-specific fields
  };
}

/**
 * Transform legacy update request to new format
 */
export function transformLegacyUpdateRequest(
  legacy: LegacyUpdateWorkoutRequest
): NewUpdateWorkoutRequest {
  if (!legacy.data.type) {
    throw new Error('Workout type is required for updates');
  }

  const workoutType = WORKOUT_TYPE_MAP[legacy.data.type] || 'STRENGTH';
  
  const workoutData: any = {};
  
  // Map common fields
  if (legacy.data.title) workoutData.name = legacy.data.title;
  if (legacy.data.description) workoutData.description = legacy.data.description;
  if (legacy.data.scheduledDate) workoutData.scheduledDate = new Date(legacy.data.scheduledDate);
  if (legacy.data.location) workoutData.location = legacy.data.location;
  if (legacy.data.estimatedDuration) workoutData.estimatedDuration = legacy.data.estimatedDuration;
  if (legacy.data.playerIds) workoutData.assignedPlayerIds = legacy.data.playerIds;
  if (legacy.data.teamId) workoutData.assignedTeamIds = [legacy.data.teamId];
  if (legacy.data.exercises) workoutData.exercises = legacy.data.exercises;
  if (legacy.data.settings) workoutData.settings = legacy.data.settings;

  // Add type-specific fields
  if (legacy.data.intervalProgram) workoutData.intervalProgram = legacy.data.intervalProgram;
  if (legacy.data.hybridProgram) workoutData.hybridProgram = legacy.data.hybridProgram;
  if (legacy.data.agilityProgram) workoutData.agilityProgram = legacy.data.agilityProgram;

  return {
    id: legacy.id,
    type: workoutType,
    workout: workoutData,
  };
}

/**
 * Transform new list request to legacy format
 */
export function transformToLegacyListParams(request: ListWorkoutsRequest): Record<string, any> {
  const params: Record<string, any> = {};
  
  // Pagination
  if (request.pagination?.page) params.page = request.pagination.page;
  if (request.pagination?.limit) params.limit = request.pagination.limit;
  if (request.pagination?.sortBy) params.sortBy = request.pagination.sortBy;
  if (request.pagination?.sortOrder) params.sortOrder = request.pagination.sortOrder;
  
  // Filters
  if (request.filters?.search) params.search = request.filters.search;
  if (request.filters?.dateFrom) params.dateFrom = request.filters.dateFrom;
  if (request.filters?.dateTo) params.dateTo = request.filters.dateTo;
  if (request.filters?.playerIds) params.playerId = request.filters.playerIds.join(',');
  if (request.filters?.teamIds) params.teamId = request.filters.teamIds.join(',');
  if (request.filters?.status) params.status = request.filters.status;
  
  // Transform workout types to legacy format
  if (request.filters?.types) {
    params.type = request.filters.types
      .map(type => LEGACY_TYPE_MAP[type])
      .filter(Boolean)
      .join(',');
  }
  
  return params;
}

// ============================================
// Response Transformations
// ============================================

/**
 * Transform legacy workout session to unified workout format
 */
export function transformLegacyWorkoutSession(session: WorkoutSession): UnifiedWorkout {
  const workoutType = WORKOUT_TYPE_MAP[session.type || 'strength'] || 'STRENGTH';
  
  const baseWorkout = {
    id: session.id,
    type: workoutType,
    name: session.title,
    description: session.description,
    scheduledDate: session.scheduledDate ? new Date(session.scheduledDate) : undefined,
    location: session.location,
    estimatedDuration: session.estimatedDuration,
    assignedPlayerIds: session.playerIds || [],
    assignedTeamIds: session.teamId ? [session.teamId] : [],
    exercises: session.exercises || [],
    settings: session.settings,
    createdAt: session.createdAt ? new Date(session.createdAt) : new Date(),
    updatedAt: session.updatedAt ? new Date(session.updatedAt) : new Date(),
  };

  // Add type-specific fields based on workout type
  switch (workoutType) {
    case 'CONDITIONING':
      return {
        ...baseWorkout,
        type: 'CONDITIONING' as const,
        intervalProgram: (session as any).intervalProgram,
      };
    
    case 'HYBRID':
      return {
        ...baseWorkout,
        type: 'HYBRID' as const,
        hybridProgram: (session as any).hybridProgram,
      };
    
    case 'AGILITY':
      return {
        ...baseWorkout,
        type: 'AGILITY' as const,
        agilityProgram: (session as any).agilityProgram,
      };
    
    default:
      return {
        ...baseWorkout,
        type: 'STRENGTH' as const,
      };
  }
}

/**
 * Transform legacy training session to unified workout format
 */
export function transformLegacyTrainingSession(session: TrainingSession): UnifiedWorkout {
  // Convert legacy TrainingSession to WorkoutSession first
  const workoutSession: WorkoutSession = {
    id: session.id,
    title: session.name,
    description: session.description,
    type: session.type,
    scheduledDate: session.date,
    location: session.location,
    teamId: session.teamId,
    playerIds: session.playerIds || [],
    estimatedDuration: session.duration,
    exercises: session.exercises || [],
    settings: session.settings,
    createdAt: session.createdAt,
    updatedAt: session.updatedAt,
  };
  
  return transformLegacyWorkoutSession(workoutSession);
}

/**
 * Transform unified workout back to legacy format
 */
export function transformToLegacyWorkoutSession(workout: UnifiedWorkout): WorkoutSession {
  return {
    id: workout.id,
    title: workout.name,
    description: workout.description,
    type: LEGACY_TYPE_MAP[workout.type],
    scheduledDate: workout.scheduledDate?.toISOString(),
    location: workout.location,
    teamId: workout.assignedTeamIds?.[0],
    playerIds: workout.assignedPlayerIds || [],
    estimatedDuration: workout.estimatedDuration,
    exercises: workout.exercises || [],
    settings: workout.settings,
    createdAt: workout.createdAt?.toISOString(),
    updatedAt: workout.updatedAt?.toISOString(),
    // Add type-specific fields
    ...(workout.type === 'CONDITIONING' && { intervalProgram: (workout as any).intervalProgram }),
    ...(workout.type === 'HYBRID' && { hybridProgram: (workout as any).hybridProgram }),
    ...(workout.type === 'AGILITY' && { agilityProgram: (workout as any).agilityProgram }),
  };
}

// ============================================
// Error Handling
// ============================================

/**
 * Transform legacy API errors to new standardized format
 */
export function transformLegacyError(error: any): any {
  if (isApiError(error)) {
    return error; // Already in new format
  }

  // Transform legacy error format
  const standardError = {
    error: {
      code: error.code || 'LEGACY_ERROR',
      message: error.message || 'An error occurred',
      details: error.details || {},
      timestamp: new Date().toISOString(),
      path: error.path || 'unknown',
      requestId: `legacy_${Date.now()}`,
    }
  };

  return standardError;
}

// ============================================
// Validation Helpers
// ============================================

/**
 * Validate that a workout can be migrated
 */
export function canMigrateWorkout(workout: any): boolean {
  try {
    // Check required fields
    if (!workout.id || !workout.name) return false;
    
    // Check if type can be mapped
    if (workout.type && !WORKOUT_TYPE_MAP[workout.type]) return false;
    
    return true;
  } catch {
    return false;
  }
}

/**
 * Get migration warnings for a workout
 */
export function getMigrationWarnings(workout: any): string[] {
  const warnings: string[] = [];
  
  if (!workout.type) {
    warnings.push('Workout type not specified, defaulting to STRENGTH');
  }
  
  if (workout.type && !WORKOUT_TYPE_MAP[workout.type]) {
    warnings.push(`Unknown workout type '${workout.type}', defaulting to STRENGTH`);
  }
  
  if (!workout.scheduledDate) {
    warnings.push('No scheduled date specified');
  }
  
  if (!workout.location) {
    warnings.push('No location specified');
  }
  
  if (!workout.assignedPlayerIds?.length && !workout.assignedTeamIds?.length) {
    warnings.push('No players or teams assigned');
  }
  
  return warnings;
}

// ============================================
// Batch Migration
// ============================================

/**
 * Migrate multiple workouts in batch
 */
export function batchMigrateWorkouts(
  workouts: (WorkoutSession | TrainingSession)[]
): {
  successful: UnifiedWorkout[];
  failed: Array<{ workout: any; error: string; warnings: string[] }>;
} {
  const successful: UnifiedWorkout[] = [];
  const failed: Array<{ workout: any; error: string; warnings: string[] }> = [];
  
  workouts.forEach(workout => {
    try {
      if (!canMigrateWorkout(workout)) {
        failed.push({
          workout,
          error: 'Workout cannot be migrated due to missing required fields',
          warnings: getMigrationWarnings(workout),
        });
        return;
      }
      
      let migratedWorkout: UnifiedWorkout;
      
      // Determine type and migrate appropriately
      if ('name' in workout) {
        // TrainingSession
        migratedWorkout = transformLegacyTrainingSession(workout as TrainingSession);
      } else {
        // WorkoutSession
        migratedWorkout = transformLegacyWorkoutSession(workout as WorkoutSession);
      }
      
      successful.push(migratedWorkout);
    } catch (error) {
      failed.push({
        workout,
        error: error instanceof Error ? error.message : 'Unknown migration error',
        warnings: getMigrationWarnings(workout),
      });
    }
  });
  
  return { successful, failed };
}

// ============================================
// Utility Functions
// ============================================

/**
 * Check if request uses legacy format
 */
export function isLegacyRequest(request: any): boolean {
  // Legacy requests typically have 'title' instead of 'name'
  return 'title' in request || 'name' in request && !('type' in request && typeof request.type === 'string' && request.type.includes('_'));
}

/**
 * Get default workout type for migration
 */
export function getDefaultWorkoutType(): WorkoutType {
  return 'STRENGTH';
}

/**
 * Create migration report
 */
export function createMigrationReport(
  successful: any[],
  failed: any[]
): {
  totalProcessed: number;
  successCount: number;
  failureCount: number;
  successRate: number;
  commonErrors: string[];
  recommendations: string[];
} {
  const totalProcessed = successful.length + failed.length;
  const successRate = totalProcessed > 0 ? (successful.length / totalProcessed) * 100 : 0;
  
  // Analyze common errors
  const errorCounts = failed.reduce((acc, item) => {
    acc[item.error] = (acc[item.error] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
  
  const commonErrors = Object.entries(errorCounts)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 5)
    .map(([error]) => error);
  
  // Generate recommendations
  const recommendations: string[] = [];
  
  if (successRate < 50) {
    recommendations.push('Migration success rate is low. Review data quality and required fields.');
  }
  
  if (commonErrors.includes('Workout type not specified')) {
    recommendations.push('Specify workout types for better migration accuracy.');
  }
  
  if (failed.some(item => item.warnings.includes('No players or teams assigned'))) {
    recommendations.push('Ensure workouts have proper player/team assignments.');
  }
  
  return {
    totalProcessed,
    successCount: successful.length,
    failureCount: failed.length,
    successRate: Math.round(successRate * 100) / 100,
    commonErrors,
    recommendations,
  };
}

export default {
  transformLegacyCreateRequest,
  transformLegacyUpdateRequest,
  transformToLegacyListParams,
  transformLegacyWorkoutSession,
  transformLegacyTrainingSession,
  transformToLegacyWorkoutSession,
  transformLegacyError,
  canMigrateWorkout,
  getMigrationWarnings,
  batchMigrateWorkouts,
  isLegacyRequest,
  getDefaultWorkoutType,
  createMigrationReport,
};