// Export base components
export { Icon, createIcon } from './Icon';
export type { IconProps } from './Icon';
export { IconSprite, SpriteIcon } from './IconSprite';

// Export individual icon components from icons subdirectory
export { Activity } from './icons/Activity';
export { AlertCircle } from './icons/AlertCircle';
export { AlertTriangle } from './icons/AlertTriangle';
export { ArrowLeft } from './icons/ArrowLeft';
export { ArrowRight } from './icons/ArrowRight';
export { ArrowUp } from './icons/ArrowUp';
export { ArrowDown } from './icons/ArrowDown';
export { BarChart3 } from './icons/BarChart3';
export { Battery } from './icons/Battery';
export { BatteryLow } from './icons/BatteryLow';
export { Bell } from './icons/Bell';
export { Brain } from './icons/Brain';
export { Calendar } from './icons/Calendar';
export { CalendarDays } from './icons/CalendarDays';
export { CalendarCheck } from './icons/CalendarCheck';
export { CalendarRange } from './icons/CalendarRange';
export { CheckCircle } from './icons/CheckCircle';
export { CheckCircle2 } from './icons/CheckCircle2';
export { ChevronDown } from './icons/ChevronDown';
export { Code2 } from './icons/Code2';
export { ChevronLeft } from './icons/ChevronLeft';
export { ChevronRight } from './icons/ChevronRight';
export { Circle } from './icons/Circle';
export { ChevronUp } from './icons/ChevronUp';
export { Clipboard } from './icons/Clipboard';
export { Clock } from './icons/Clock';
export { Coffee } from './icons/Coffee';
export { Copy } from './icons/Copy';
export { Crown } from './icons/Crown';
export { Database } from './icons/Database';
export { Download } from './icons/Download';
export { Dumbbell } from './icons/Dumbbell';
export { Edit } from './icons/Edit';
export { ExternalLink } from './icons/ExternalLink';
export { Eye } from './icons/Eye';
export { EyeOff } from './icons/EyeOff';
export { File } from './icons/File';
export { FileImage } from './icons/FileImage';
export { FileSpreadsheet } from './icons/FileSpreadsheet';
export { FileText } from './icons/FileText';
export { Filter } from './icons/Filter';
export { Flag } from './icons/Flag';
export { FolderOpen } from './icons/FolderOpen';
export { Gamepad2 } from './icons/Gamepad2';
export { Gauge } from './icons/Gauge';
export { Globe } from './icons/Globe';
export { Grid } from './icons/Grid';
export { Grid3X3 } from './icons/Grid3X3';
export { GripVertical } from './icons/GripVertical';
export { Heart } from './icons/Heart';
export { HelpCircle } from './icons/HelpCircle';
export { History } from './icons/History';
export { Info } from './icons/Info';
export { Layers } from './icons/Layers';
export { Layout } from './icons/Layout';
export { Library } from './icons/Library';
export { List } from './icons/List';
export { Loader2 } from './icons/Loader2';
export { Lock } from './icons/Lock';
export { MapPin } from './icons/MapPin';
export { Maximize2 } from './icons/Maximize2';
export { Megaphone } from './icons/Megaphone';
export { Minimize2 } from './icons/Minimize2';
export { MessageSquare } from './icons/MessageSquare';
export { Monitor } from './icons/Monitor';
export { MoreHorizontal } from './icons/MoreHorizontal';
export { MoreVertical } from './icons/MoreVertical';
export { Move } from './icons/Move';
export { MoveDown } from './icons/MoveDown';
export { MoveUp } from './icons/MoveUp';
export { Pause } from './icons/Pause';
export { PauseCircle } from './icons/PauseCircle';
export { Play } from './icons/Play';
export { PlayCircle } from './icons/PlayCircle';
export { Plus } from './icons/Plus';
export { Printer } from './icons/Printer';
export { RotateCcw } from './icons/RotateCcw';
export { RotateCw } from './icons/RotateCw';
export { Save } from './icons/Save';
export { Search } from './icons/Search';
export { Send } from './icons/Send';
export { Settings } from './icons/Settings';
export { Smartphone } from './icons/Smartphone';
export { Target } from './icons/Target';
export { TestTube2 } from './icons/TestTube2';
export { Timer } from './icons/Timer';
export { Trash2 } from './icons/Trash2';
export { TrendingDown } from './icons/TrendingDown';
export { Trophy } from './icons/Trophy';
export { RefreshCw } from './icons/RefreshCw';
export { Upload } from './icons/Upload';
export { User } from './icons/User';
export { Users } from './icons/Users';
export { Video } from './icons/Video';
export { Volume2 } from './icons/Volume2';
export { VolumeX } from './icons/VolumeX';
export { X } from './icons/X';
export { XCircle } from './icons/XCircle';
export { Zap } from './icons/Zap';
export { TrendingUp } from './icons/TrendingUp';
export { Shield } from './icons/Shield';
export { Wind } from './icons/Wind';
export { Keyboard } from './icons/Keyboard';
export { Star } from './icons/Star';
export { Flame } from './icons/Flame';
export { Share2 } from './icons/Share2';
export { LineChart } from './icons/LineChart';
export { ThumbsUp } from './icons/ThumbsUp';
export { ThumbsDown } from './icons/ThumbsDown';
export { PieChart } from './icons/PieChart';
export { Award } from './icons/Award';
export { Package } from './icons/Package';
export { Calculator } from './icons/Calculator';
export { Share } from './icons/Share';
export { Hammer } from './icons/Hammer';
export { Waves } from './icons/Waves';
export { BarChart } from './icons/BarChart';
export { Undo } from './icons/Undo';
export { Redo } from './icons/Redo';
export { Check } from './icons/Check';
export { Repeat } from './icons/Repeat';
export { Wrench } from './icons/Wrench';
export { Lightbulb } from './icons/Lightbulb';
export { Shuffle } from './icons/Shuffle';
export { Sparkles } from './icons/Sparkles';
export { UserCheck } from './icons/UserCheck';
export { UserX } from './icons/UserX';
export { Square } from './icons/Square';
export { Minus } from './icons/Minus';
export { SkipBack } from './icons/SkipBack';
export { SkipForward } from './icons/SkipForward';
export { StepBack } from './icons/StepBack';
export { StepForward } from './icons/StepForward';
export { MousePointer } from './icons/MousePointer';
export { QrCode } from './icons/QrCode';
export { Book } from './icons/Book';
export { BookOpen } from './icons/BookOpen';
export { MessageCircle } from './icons/MessageCircle';
export { Palette } from './icons/Palette';
export { Snowflake } from './icons/Snowflake';

// Convenience re-exports with commonly used aliases
export { Edit as EditIcon } from './icons/Edit';
export { Trash2 as TrashIcon } from './icons/Trash2';
export { Plus as PlusIcon } from './icons/Plus';
export { Save as SaveIcon } from './icons/Save';
export { Download as DownloadIcon } from './icons/Download';
export { Upload as UploadIcon } from './icons/Upload';
export { CheckCircle as CheckCircleIcon } from './icons/CheckCircle';
export { AlertCircle as AlertCircleIcon } from './icons/AlertCircle';
export { ChevronDown as ChevronDownIcon } from './icons/ChevronDown';
export { ChevronUp as ChevronUpIcon } from './icons/ChevronUp';