import { SVGProps } from 'react';

export interface IconProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
  color?: string;
}

export type IconComponent = React.FC<IconProps>;

// Icon names for type safety
export type IconName = 
  | 'plus'
  | 'save'
  | 'edit'
  | 'trash2'
  | 'download'
  | 'upload'
  | 'check-circle'
  | 'alert-circle'
  | 'chevron-down'
  | 'chevron-up'
  | 'settings'
  | 'play'
  | 'pause'
  | 'eye'
  | 'heart'
  | 'calendar'
  | 'clock'
  | 'users'
  | 'user'
  | 'x'
  | 'search'
  | 'filter'
  | 'copy'
  | 'clipboard'
  | 'file-text'
  | 'folder'
  | 'archive'
  | 'activity'
  | 'bar-chart'
  | 'target'
  | 'trending-up'
  | 'info'
  | 'help-circle'
  | 'alert-triangle'
  | 'check'
  | 'minus'
  | 'maximize'
  | 'minimize'
  | 'refresh-cw'
  | 'loader'
  | 'menu'
  | 'more-vertical'
  | 'more-horizontal'
  | 'grid'
  | 'list'
  | 'layers'
  | 'share'
  | 'external-link'
  | 'link'
  | 'zap'
  | 'star'
  | 'message-circle'
  | 'bell'
  | 'inbox'
  | 'send'
  | 'printer'
  | 'file'
  | 'image'
  | 'video'
  | 'mic'
  | 'headphones'
  | 'volume'
  | 'volume-2'
  | 'wifi'
  | 'battery'
  | 'bluetooth'
  | 'cast'
  | 'phone'
  | 'mail'
  | 'globe'
  | 'map-pin'
  | 'navigation'
  | 'compass'
  | 'home'
  | 'book'
  | 'bookmark'
  | 'flag'
  | 'award'
  | 'gift'
  | 'package'
  | 'shopping-cart'
  | 'credit-card'
  | 'dollar-sign'
  | 'percent'
  | 'hash'
  | 'at-sign'
  | 'bold'
  | 'italic'
  | 'underline'
  | 'code'
  | 'terminal'
  | 'cpu'
  | 'hard-drive'
  | 'server';