apiVersion: v1
kind: Namespace
metadata:
  name: hockey-hub
  labels:
    name: hockey-hub
    app.kubernetes.io/name: hockey-hub
    app.kubernetes.io/version: "1.0.0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: hockey-hub-quota
  namespace: hockey-hub
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "20"
    services: "20"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: hockey-hub-limits
  namespace: hockey-hub
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container