apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: hockey-hub
data:
  init.sql: |
    -- Create databases for all services
    CREATE DATABASE hockey_hub_users;
    CREATE DATABASE hockey_hub_communication;
    CREATE DATABASE hockey_hub_calendar;
    CREATE DATABASE hockey_hub_training;
    CREATE DATABASE hockey_hub_medical;
    CREATE DATABASE hockey_hub_planning;
    CREATE DATABASE hockey_hub_statistics;
    CREATE DATABASE hockey_hub_payment;
    CREATE DATABASE hockey_hub_admin;
    CREATE DATABASE hockey_hub_files;
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: hockey-hub
  labels:
    app: postgres
    component: database
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hockey-hub-secrets
              key: DB_PASSWORD
        - name: POSTGRES_INITDB_ARGS
          value: "--auth-host=scram-sha-256"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: postgres-init
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U postgres -h 127.0.0.1 -p 5432
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U postgres -h 127.0.0.1 -p 5432
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
      volumes:
      - name: postgres-init
        configMap:
          name: postgres-init
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "fast-ssd"
      resources:
        requests:
          storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: hockey-hub
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
---
# Service for external access (if needed)
apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: hockey-hub
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP