# This is a template file for secrets
# DO NOT commit actual secrets to version control
# Use kubectl create secret or external secret management

apiVersion: v1
kind: Secret
metadata:
  name: hockey-hub-secrets
  namespace: hockey-hub
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  DB_PASSWORD: cGxlYXNlLWNoYW5nZS1tZQ==  # please-change-me
  JWT_SECRET: cGxlYXNlLWNoYW5nZS1tZQ==   # please-change-me
  JWT_PUBLIC_KEY: cGxlYXNlLWNoYW5nZS1tZQ== # please-change-me
  REDIS_PASSWORD: cGxlYXNlLWNoYW5nZS1tZQ== # please-change-me
  ENCRYPTION_KEY: cGxlYXNlLWNoYW5nZS1tZQ==  # please-change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: email-secrets
  namespace: hockey-hub
type: Opaque
data:
  SMTP_HOST: c210cC5zZW5kZ3JpZC5uZXQ=     # smtp.sendgrid.net
  SMTP_PORT: NTg3                        # 587
  SMTP_USER: YXBpa2V5                    # apikey
  SMTP_PASS: cGxlYXNlLWNoYW5nZS1tZQ==    # please-change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: hockey-hub
type: Opaque
data:
  AWS_ACCESS_KEY_ID: cGxlYXNlLWNoYW5nZS1tZQ==     # please-change-me
  AWS_SECRET_ACCESS_KEY: cGxlYXNlLWNoYW5nZS1tZQ== # please-change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: hockey-hub
type: Opaque
data:
  STRIPE_SECRET_KEY: cGxlYXNlLWNoYW5nZS1tZQ==      # please-change-me
  STRIPE_PUBLISHABLE_KEY: cGxlYXNlLWNoYW5nZS1tZQ==  # please-change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: sms-secrets
  namespace: hockey-hub
type: Opaque
data:
  TWILIO_ACCOUNT_SID: cGxlYXNlLWNoYW5nZS1tZQ==     # please-change-me
  TWILIO_AUTH_TOKEN: cGxlYXNlLWNoYW5nZS1tZQ==      # please-change-me
  TWILIO_PHONE_NUMBER: cGxlYXNlLWNoYW5nZS1tZQ==    # please-change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: hockey-hub
type: Opaque
data:
  GRAFANA_PASSWORD: cGxlYXNlLWNoYW5nZS1tZQ==       # please-change-me