name: Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    
jobs:
  check-commit-message:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Check commit message format
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.json 